name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.1.2
  - numpy=1.23.5
  - mlflow=1.14.1
  - scikit-learn=0.24.2
  - matplotlib=3.6.1
  - pillow=9.5.0
  - pip:
      - wandb==0.12.17